"""Streamlit client of the same RAG pipeline used by the experiment runner."""
import hmac
import json
import os
import sys
from pathlib import Path

# `streamlit run app/app.py` (Community Cloud) puts only app/ on sys.path; the src package lives at the root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd  # noqa: E402
import streamlit as st  # noqa: E402

from src.agent.cache import ResultCache  # noqa: E402
from src.agent.llm import llm_descriptor  # noqa: E402
from src.retrieval.corpus import PDF_PATH  # noqa: E402
from src.retrieval.pipeline import ElectionRAG, rag_fingerprint  # noqa: E402

st.set_page_config(page_title="CI Election Chatbot 2025", page_icon="🗳️", layout="wide")

# Community Cloud passes settings as secrets; root-level keys become environment variables once loaded.
try:
    st.secrets.load_if_toml_exists()
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[1]
SAVED_RUN = ROOT / 'experiments/runs/text-to-sql-comparison-haiku-20260930'
# PUBLIC_DEMO=1: no model client is ever built. APP_ACCESS_CODE: live answers only after entering the code.
PUBLIC_DEMO = os.getenv('PUBLIC_DEMO', '').strip().lower() in {'1', 'true', 'yes'}
ACCESS_CODE = os.getenv('APP_ACCESS_CODE', '').strip()

MODES = {'A': 'Sans RAG · catalogue fixe', 'B': 'RAG · BM25 (recommandé)',
         'C': 'RAG · E5 sémantique', 'D': 'RAG · hybride BM25 + E5'}
SHORT = {'A': 'Sans RAG', 'B': 'BM25', 'C': 'E5', 'D': 'Hybride'}
# From the saved evaluation: A answered these correctly; A failed the RAG ones (place spellings), BM25 did not.
EXAMPLES_WITHOUT_RAG = ['dev-003', 'dev-009', 'dev-015']
EXAMPLES_NEED_RAG = ['dev-001', 'dev-011', 'dev-019']
OUTCOME_LABEL = {'correct': '✅ correct', 'correct_abstention': '✅ refus correct', 'wrong_result': '❌ résultat faux',
                 'wrong_abstention': '❌ refus injustifié', 'missed_abstention': '❌ aurait dû refuser'}


@st.cache_data
def saved_answers():
    """Answers generated by Claude Haiku 4.5 in the archived evaluation run (no new calls)."""
    records = {json.loads(l)['id']: json.loads(l) for l in (ROOT / 'benchmarks/edan_2025_v1.jsonl').open()}
    out = {}
    for line in (SAVED_RUN / 'traces.jsonl').open():
        t = json.loads(line)
        out[(t['question_id'], t['condition'])] = {
            'question': records[t['question_id']]['question'], 'answerability': t.get('answerability'),
            'ok': t['executed'], 'status': t['status'], 'response': t.get('response'),
            'final_sql': t.get('final_sql'), 'columns': t.get('columns'), 'rows': t.get('rows'),
            'outcome': t['outcome'], 'success': t['success'], 'error': t.get('error'), 'stage': t.get('stage'),
            'context_ids': t.get('context_ids', []), 'condition': t['condition'], 'saved': True,
            'served_by': ['Claude Haiku 4.5']}
    return out


@st.cache_resource
def init_rag(version, condition):
    return ElectionRAG(condition)


def get_rag(condition):
    return init_rag(rag_fingerprint(condition), condition)


for key, value in (('result_cache', ResultCache()), ('messages', [])):
    st.session_state.setdefault(key, value)

# ---------------------------------------------------------------- sidebar: only the relevant options
with st.sidebar:
    st.header('Options')
    default = os.getenv('RAG_CONDITION', 'B')
    condition = st.selectbox('Mode de recherche', list(MODES), format_func=MODES.get, key='mode',
                             index=list(MODES).index(default) if default in MODES else 1)
    show_sql = st.toggle('Afficher la requête SQL', value=True)
    unlocked = not ACCESS_CODE
    if ACCESS_CODE and not PUBLIC_DEMO:
        code = st.text_input("Code d'accès", type='password', help='Requis pour interroger le modèle Gemini.')
        unlocked = bool(code) and hmac.compare_digest(code, ACCESS_CODE)
    LIVE = not PUBLIC_DEMO and unlocked
    if LIVE:
        st.success(f"Réponses en direct · {llm_descriptor()['primary'] or 'Gemini non configuré'}")
    elif PUBLIC_DEMO:
        st.caption('Mode démonstration : réponses issues de l’évaluation enregistrée.')
    else:
        st.caption("Entrez le code d'accès pour des réponses en direct.")
    if st.button("Effacer l'historique"):
        st.session_state.messages = []
        st.session_state.result_cache.clear()
        st.rerun()
    if PDF_PATH.exists():
        st.download_button('Télécharger le PDF source', PDF_PATH.read_bytes(), file_name=PDF_PATH.name,
                           mime='application/pdf')

try:
    rag = get_rag(condition)
except Exception as exc:
    st.error(f'Initialisation du RAG : {exc}')
    st.info('Préparer les données : python -m src.preprocessing puis python -m src.model_training --prepare-encoder')
    st.stop()


# ---------------------------------------------------------------- rendering
def render_sources(sources):
    with st.expander(f'Contexte retrouvé · {len(sources)} fiches'):
        for card in sources:
            st.markdown(f"**{card['title']}** · `{card['id']}`")
            st.text(card['text'])


def render_result(out, compact=False):
    if out.get('saved') and not compact:
        st.caption(f"Réponse enregistrée (Claude Haiku 4.5, évaluation du 30/09/2026) · mode {SHORT[out['condition']]}"
                   f" · {OUTCOME_LABEL.get(out['outcome'], out['outcome'])}")
    if out.get('status') == 'search':
        st.info('Contexte que le modèle recevrait pour cette question. Les réponses SQL en direct sont désactivées ; '
                'essayez un exemple ci-dessus ou l’onglet « Réponses enregistrées ».')
    elif out.get('status') in {'unsupported', 'needs_clarification'}:
        st.info(out['response'])
    elif not out.get('ok'):
        st.error('Impossible de répondre à cette question.')
        st.caption(f"{out.get('stage', 'application')} : {(out.get('error') or 'erreur inconnue')[:300]}")
    else:
        df = pd.DataFrame(out['rows'], columns=out['columns'])
        if not compact:
            served = ', '.join(out.get('served_by') or []) or 'modèle'
            st.success(f"{len(df)} ligne(s) · {served}" + (' · réponse en cache' if out.get('cache_hit') else ''))
        st.dataframe(df, width='stretch', hide_index=True)
        if show_sql:
            st.code(out.get('final_sql') or '', language='sql', wrap_lines=compact)
    if compact:
        return
    sources = out.get('sources') or [rag.builder.by_id[c] for c in out.get('context_ids', []) if c in rag.builder.by_id]
    if sources:
        render_sources(sources)
    if out.get('fallback_used'):
        st.warning('Réponse produite par le modèle de secours Claude (API payante) : Gemini était indisponible.')


def answer(question, cond, example_id=None):
    """Live answer when allowed; otherwise the saved answer for examples, or retrieval-only context."""
    try:
        if LIVE:
            out = st.session_state.result_cache.query(question, rag_fingerprint(cond), get_rag(cond).run_query)
            return {**out, 'condition': cond}
        if example_id:
            return saved_answers()[(example_id, cond)]
        return {'ok': True, 'status': 'search', 'sources': get_rag(cond).search(question), 'condition': cond}
    except Exception as exc:
        return {'ok': False, 'stage': 'application', 'error': str(exc), 'condition': cond}


def ask(question, cond, example_id=None):
    st.session_state.messages.append({'role': 'user', 'content': f"{question}  \n*mode : {MODES[cond]}*"})
    with st.spinner('Recherche dans les sources…'):
        st.session_state.messages.append({'role': 'assistant', 'result': answer(question, cond, example_id)})


# ---------------------------------------------------------------- page
st.title("Côte d'Ivoire 2025 — Election Chatbot")
st.caption('Chaque question est indépendante. Les résultats concernent des candidatures/listes, pas des sièges.')
tab_chat, tab_saved = st.tabs(['💬 Poser une question', '📊 Réponses enregistrées (évaluation)'])

with tab_chat:
    saved = saved_answers()
    left, right = st.columns(2)
    with left:
        st.markdown('**Fonctionnent sans RAG** · mode A')
        for qid in EXAMPLES_WITHOUT_RAG:
            if st.button(saved[(qid, 'A')]['question'], key=f'ex-{qid}', width='stretch'):
                ask(saved[(qid, 'A')]['question'], 'A', qid)
    with right:
        st.markdown('**Nécessitent le RAG** · échouent sans RAG, réussissent avec BM25')
        for qid in EXAMPLES_NEED_RAG:
            if st.button(saved[(qid, 'B')]['question'], key=f'ex-{qid}', width='stretch'):
                ask(saved[(qid, 'B')]['question'], 'B', qid)
    history = st.container()
    prompt = st.chat_input('Pose ta question sur les résultats électoraux')
    if prompt:
        ask(prompt, condition)
    with history:
        for message in st.session_state.messages:
            with st.chat_message(message['role']):
                if 'result' in message:
                    render_result(message['result'])
                else:
                    st.markdown(message['content'])

with tab_saved:
    saved = saved_answers()
    questions = sorted({qid for qid, _ in saved})
    st.markdown('Évaluation du 30/09/2026 : **Claude Haiku 4.5** a généré la SQL pour **18 questions de '
                'développement** dans les quatre modes (une exécution par mode). Aucun nouvel appel n’est fait ici.')
    metrics = st.columns(4)
    for col, cond in zip(metrics, MODES):
        answerable = [saved[(q, cond)] for q in questions if saved[(q, cond)]['answerability'] == 'answerable']
        correct = sum(a['outcome'] == 'correct' for a in answerable)
        col.metric(f'{SHORT[cond]} · SQL correcte', f'{correct}/{len(answerable)}')
    grid = pd.DataFrame([{'Question': saved[(q, 'A')]['question'],
                          **{SHORT[c]: '✅' if saved[(q, c)]['success'] else '❌' for c in MODES}} for q in questions])
    st.dataframe(grid, width='stretch', hide_index=True, height=35 * (len(grid) + 1) + 3)
    picked = st.selectbox('Comparer les quatre modes pour une question', questions,
                          index=questions.index('dev-001'), format_func=lambda q: saved[(q, 'A')]['question'])
    for col, cond in zip(st.columns(4), MODES):
        with col:
            item = saved[(picked, cond)]
            st.markdown(f"**{MODES[cond]}**  \n{OUTCOME_LABEL.get(item['outcome'], item['outcome'])}")
            render_result(item, compact=True)
